### ISSUE TITLE
related collections and models gets reinstantiated on every fetch

### ISSUE THREAD

**Issue by coolov** [RNGR/directus6#330]
make sure that they get reset instead

**Comment by benhaynes** [comment]
This was unclear so I reached out to Jason, he said:

"It's a minor optimization that I don't think would make much of a performance gain. It's basically just re-creating a collection, rather than just resetting the object, so I doubt it will make any differences."

So I'll close it for now, we might get into this type of work in the future when truly in optimization mode.
