### ISSUE TITLE
Default to schema default item status ui

### ISSUE THREAD

**Issue by jel-massih** [RNGR/directus6#410]

**Comment by benhaynes** [comment]
@WellingGuzman This should be adjusted so that the default status for a table (if the table has a status column) comes from the status column's default value. So if Table_A has an `active` column, and the default value for that column is "2" then all new items created in that table would default to "inactive".

This also means that we would remove the `default_status` under `directus_tables` and any references to it.

**Comment by benhaynes** [comment]
Also, works perfectly. Though we should try to incorporate console.log()s for times when settings seem off. For example, it would be ideal (but not necessary) if Directus would send a console.log when the default active value didn't match the status options. Not needed at all for now though... we can always make another ticket later.

Thanks!
