### ISSUE TITLE
Many-to-many UI is always required?

### ISSUE THREAD

**Issue by benhaynes** [RNGR/directus6#612]
For some reason, the many-to-many UI is forcing itself to be required. The "required" checkbox within settings is disabled... and if you override it in the database (directus_tables) it is **still** required. I believe this was because of *allow_null* for many-to-ones... but this **shouldn't** apply to many-to-manys.

**http://directus.rngr.org/tables/fitness**
Try to delete the image under slideshow and then save...

**Comment by WellingGuzman** [comment]
When the column can't be null, it would be automatically required, what could be a better way t handle this? let the be like this or if it's not required and it's a M2M column, not bother if it's nullify or not, because we store it in tables rows, not in single column.

What do you think @benhaynes ?

**Comment by benhaynes** [comment]
Hey @WellingGuzman – I agree, I think it's important for M2O to be required when there's no ALLOW NULL... but for M2M it doesn't matter since they are individual rows.

The only problem is that the settings page still disables the Required option checkbox for M2M (so you have to change it directly in the DB for now:
![disabled-required-checkbox](https://cloud.githubusercontent.com/assets/522079/5939301/7d9907c0-a6d0-11e4-8d31-3d532bda0a2c.gif)

**Comment by benhaynes** [comment]
Looks good!
